### ISSUE TITLE
Consider renaming the project

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-network#233]
### Describe the issue you're reporting

The project name is "opentelemetry-ebpf", but multiple other projects associated with OpenTelemetry use eBPF as foundational technology for other purposes such as instrumenting Go applications. We should probably rename this project to opentelemetry-networking-monitoring, or an equivalent name, that focuses on the use case of the project rather than the underlying tech.

**Comment by JaredTan95** [comment]
That makes sense, I agree. So, Will there be a vote?

**Comment by atoulme** [comment]
This was discussed by the GC. I am proceeding to make the request official with an issue in the community project.

**Comment by codeboten** [comment]
I believe this issue can be closed now that the repo has been renamed

**Comment by JaredTan95** [comment]
> I believe this issue can be closed now that the repo has been renamed

+1
